name: Update submodule and browserify

# See https://github.community/t/workflow-dependencies-using-repository-dispatch/17817
on:
  push:
    branches: [main]
  repository_dispatch:
  workflow_dispatch:

jobs:
  update-submodule-and-browserify:
    name: Update submodule and browserify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Update and checkout rockstar submodule
        run: git submodule update --init --remote docs/rockstar

      - name: Browserify rockstar/satriani
        working-directory: docs/rockstar/satriani
        run: |
          yarn install
          yarn browserify

      - name: Copy browserify result outside submodule
        working-directory: docs
        run: cp rockstar/satriani/satriani.standalone.js js/satriani.js

      - name: Add, commit, and push any changes
        run: |
          if ! (git status --porcelain | grep -q .) ; then
            git status
            exit 0
          fi

          git config --global user.name  "GitHub Action Workflow"
          git config --global user.email "github-action-workflow@codewithrockstar.com"

          git add --verbose .
          git commit --message "Update submodule and browserify"
          git push
